spring:
  application:
    name: static-simulator
  cloud:
    stream:
      bindings:
        input:
          destination: riders
          group: test
        riders:
          destination: riders
        cars:
          destination: cars

      kafka:
        binder:
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
#        bindings:
#          riders:
#            producer:
#              configuration:
#                key:
#                  serializer: org.apache.kafka.common.serialization.StringSerializer
#          cars:
#            producer:
#              configuration:
#                key:
#                  serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: "*"


