server.port: 8080
spring.application.name: simulator

spring.cloud.stream.bindings:
  travelers:
    destination: travelers
  travel-requests:
    destination: travel_requests
  cars:
    destination: cars

spring.cloud.stream.kafka.binder.configuration:
  key.serializer: org.apache.kafka.common.serialization.StringSerializer

management.endpoints.web.exposure.include: "*"


logging.level.io.kfleet: DEBUG
