server:
  port: 8082
spring:
  application:
    name: validator
  cloud.stream.bindings:
    input:
      destination: travel_requests
      group: test
    output:
      destination: accepted_travel_requests
  cloud.stream:
    kafka:
      binder:
        configuration:
          key:
            serializer: org.apache.kafka.common.serialization.StringSerializer

spring.cloud.stream.kafka.streams.bindings.travelers:
  consumer:
    materializedAs: all-travelers

spring.cloud.stream.kafka.streams.binder.configuration.default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.binder.configuration.default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

management:
  endpoints:
    web:
      exposure:
        include: "*"


